server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/autenticacion/**
          filters: []

        - id: employee-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/employees/**
          filters: []

        - id: insurance-type-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/insurance-types/**
          filters: []

        - id: performance-service
          uri: http://localhost:8083
          predicates:
            - Path=/performance/**
          filters: []